import SWRProvider from "@/providers/swr-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SWRProvider>
      <html lang="en">
        <body className={`${inter.className} bg-stone-900  text-stone-200`}>
          {children}
        </body>
      </html>
    </SWRProvider>
  );
}
